# Generated by Django 5.2.4 on 2025-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_order_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Deliverd'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
