# Generated by Django 5.2.4 on 2025-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_category', models.CharField(choices=[('IT', 'IT'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('OTHER', 'Other')], default='IT', max_length=20)),
                ('connection_category', models.CharField(choices=[('PARTNER', 'Partner'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('DISTRIBUTOR', 'Distributor'), ('CONSULTANT', 'Consultant'), ('OTHER', 'Other')], default='PARTNER', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
