# Generated by Django 5.2.4 on 2025-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='connections/images/'),
        ),
    ]
