# Generated by Django 5.2.4 on 2025-08-23 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
