# Generated by Django 5.2.4 on 2025-09-06 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
