# Generated by Django 5.2.4 on 2025-09-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_user'),
        ('admin_profile', '0002_adminprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsecurity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_security', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
