# Generated by Django 5.2.4 on 2025-09-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0005_companydetails_user_alter_adminprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='industry_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
