# Generated by Django 5.2.4 on 2025-09-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_colors_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
