# Generated by Django 5.2.4 on 2025-09-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
