# Generated by Django 5.2.4 on 2025-09-24 22:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0005_products_limited_deal_alter_productcategory_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_until',
            new_name='valid_to',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
