# Generated by Django 5.2.4 on 2025-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_coupon_discount_percentage_and_more'),
        ('products', '0007_alter_products_created_at_alter_products_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.products'),
        ),
    ]
