# Generated by Django 5.2.4 on 2025-09-24 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_title', models.CharField(max_length=100)),
                ('second_title', models.CharField(max_length=100)),
                ('third_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(max_length=255)),
                ('product_link', models.URLField(blank=True, max_length=255, null=True)),
                ('hero_image', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_hero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_title', models.CharField(max_length=100)),
                ('second_title', models.CharField(max_length=100)),
                ('third_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(max_length=255)),
                ('product_link', models.URLField(blank=True, max_length=255, null=True)),
                ('hero_image', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
