# Generated by Django 5.2.4 on 2025-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('b2b', 'B2B')], default='b2b', max_length=10),
        ),
    ]
