# Generated by Django 5.2.6 on 2025-09-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_image_review_name_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
