# Generated by Django 5.2.4 on 2025-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_b', '0002_remove_b2buser_company_name_b2buser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2buser',
            name='user_type',
            field=models.CharField(choices=[('b2b', 'B2B')], default='b2b', max_length=10),
        ),
    ]
