# Generated by Django 5.2.4 on 2025-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_adminsujonprofile_delete_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
