# Generated by Django 5.2.4 on 2025-09-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_companydetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsujonprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='industry_type',
            field=models.CharField(choices=[('Software industry', 'Software industry'), ('Hardware industry', 'Hardware industry'), ('Finance industry', 'Finance industry'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
