# Generated by Django 5.2.4 on 2025-09-08 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_adminsujonprofile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminSujonProfile',
            new_name='AdminProfile',
        ),
    ]
