# Generated by Django 5.2.4 on 2025-10-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_shipping_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('SUCCESS', 'Payment Successful'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
    ]
