# Generated by Django 5.2.4 on 2025-08-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_shipping_status'),
        ('orders', '0003_alter_order_options_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='orders.order'),
        ),
    ]
