# Generated by Django 5.2.4 on 2025-08-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
