# Generated by Django 5.2.4 on 2025-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_traindata_chatbotquery_delete_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
