# Generated by Django 5.2.4 on 2025-09-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_adminnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at']},
        ),
    ]
