# Generated by Django 5.2.4 on 2025-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_adminnotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
