# Generated by Django 5.2.6 on 2025-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
