# Generated by Django 5.2.4 on 2025-08-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock_quantity',
            new_name='stock',
        ),
    ]
