# Generated by Django 5.2.6 on 2025-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon for the category', null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='products',
            name='limited_deal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='limited_deal_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price during the limited deal', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='limited_deal_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
