# Generated by Django 5.2.6 on 2025-09-21 20:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_icon_products_limited_deal_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='limited_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_icons'),
        ),
    ]
