# Generated by Django 5.2.4 on 2025-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('company_name', models.EmailField(max_length=55)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
