# Generated by Django 5.2.4 on 2025-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('message', 'Message'), ('wishlist', 'Wishlist'), ('offer', 'Offer')], max_length=20, null=True),
        ),
    ]
